resources:
  - name: nanocf
    type: git
    source:
      uri: https://github.com/sclevine/nanocf
      branch: master
  - name: image-changes
    type: git
    source:
      uri: https://github.com/sclevine/nanocf
      branch: master
      paths: [build,image,micropcf,patches]

jobs:
  - name: push-app-ssd
    plan:
    - get: nanocf
      params:
        submodules: none
    - task: run
      tags: [ssd-worker]
      file: nanocf/ci/tasks/push-app/task.yml
      config:
        privileged: true

  - name: push-app-ebs
    plan:
    - get: nanocf
      params:
        submodules: none
    - task: run
      file: nanocf/ci/tasks/push-app/task.yml
      config:
        privileged: true

  - name: push-app-vsphere
    plan:
    - get: nanocf
      params:
        submodules: none
    - task: run
      tags: [vsphere-linux-worker]
      file: nanocf/ci/tasks/push-app/task.yml
      config:
        privileged: true
