resources:
  - name: nanocf
    type: git
    source:
      uri: https://github.com/sclevine/nanocf
      branch: master
  - name: image-changes
    type: git
    source:
      uri: https://github.com/sclevine/nanocf
      branch: master
      paths: [build,image,micropcf,patches]

  - name: container-volume
    type: time

jobs:
  - name: push-app-ssd
    plan:
    - get: nanocf
      params:
        submodules: none
    - task: run
      privileged: true
      tags: [ssd-worker]
      file: nanocf/ci/tasks/push-app/task.yml

  - name: push-app-ebs
    plan:
    - get: nanocf
      params:
        submodules: none
    - task: run
      privileged: true
      file: nanocf/ci/tasks/push-app/task.yml

  - name: push-app-vsphere
    plan:
    - get: nanocf
      params:
        submodules: none
    - get: container-volume
    - task: run
      privileged: true
      tags: [vsphere-linux-worker]
      file: nanocf/ci/tasks/push-app/task.yml
