resources:
  - name: nanocf
    type: git
    source:
      uri: https://github.com/sclevine/nanocf
      branch: master
  - name: image-changes
    type: git
    source:
      uri: https://github.com/sclevine/nanocf
      branch: master
      paths: [build,image,micropcf,patches]

jobs:
  - name: run-nanocf
    plan:
    - get: nanocf
      params:
        submodules: none
    - task: run
      file: nanocf/ci/tasks/run/task.yml
      config:
        privileged: true
